services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 10uzb24
      MYSQL_DATABASE: ticketsystem
    networks:
      - dockernetwork
    ports:
      - "3306:3306"
    volumes:
      - ./:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: MySQL
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 10uzb24
    networks:
      - dockernetwork
    ports:
      - "8081:81"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - dockernetwork
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - phpmyadmin
      - mysql


networks:
  dockernetwork:
    driver: bridge