services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 10uzb24
      MYSQL_DATABASE: ticketsystem
    networks:
      - dockernetwork
    ports:
      - "3306:3306"
    volumes:
      - ./:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: MySQL
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 10uzb24
    networks:
      - dockernetwork
    ports:
      - "8080:80"

networks:
  dockernetwork:
    driver: bridge